title: It Will Never Work in Theory
subtitle: Short summaries of recent results in empirical software engineering research
url: https://neverworkintheory.org
repository: neverworkintheory/neverworkintheory.github.com
repositoryurl: https://github.com/neverworkintheory/neverworkintheory.github.io/
eventbrite: https://www.eventbrite.com/e/it-will-never-work-in-theory-tickets-527743173037

markdown: kramdown
highlighter: rouge
permalink: "/:year/:month/:day/:title.html"
paginate: 10
paginate_path: /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Greg Wilson
  url: https://third-bit.com
  email: gvwilson@third-bit.com

years:
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2021
  - 2022

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - '*.sublime-*'
  - '*.aux'
  - '*.bbl'
  - '*.blg'
  - '*.log'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle
  - bin
