title: It Will Never Work in Theory
subtitle: Short summaries of recent results in empirical software engineering research
url: https://neverworkintheory.org
repository: neverworkintheory/neverworkintheory.github.com
repositoryurl: https://github.com/neverworkintheory/neverworkintheory.github.io/

markdown: kramdown
highlighter: rouge
permalink: "/:year/:month/:day/:title.html"
paginate: 10
paginate_path: /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Greg Wilson
  url: https://third-bit.com
  email: gvwilson@third-bit.com

years:
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2021

plugins:
  - jekyll-paginate

exclude:
  - '*.sublime-*'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle
